services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./itinerary_generator:/app/itinerary_generator
    depends_on:
      - gotenberg
    environment:
      - FLASK_APP=itinerary_generator.app
      - PYTHONPATH=/app

  gotenberg:
    image: gotenberg/gotenberg:7
    ports:
      - "3000:3000"