version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - gotenberg

  gotenberg:
    image: thecodingmachine/gotenberg:7
    ports:
      - "3000:3000"
