name: Auto-merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - labeled
      - synchronize

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: squash
