name: Auto-merge Dependabot PRs

permissions:
  contents: read
  pull-requests: write
  
on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Automerge PR
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMERGE_TOKEN }}
          MERGE_METHOD: squash
          MERGE_LABELS: ""
