name: Build & Push Docker Image

on:
  push:
    branches: [main]
    tags:
      - 'v*'  # optional: auto-publish if tag like v1.0.1 is pushed

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: maskedkunsiquat/itinerary-generator

      - name: Extract tag or default to latest
        id: version
        run: |
          VERSION="${GITHUB_REF##*/}"
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "tag=${VERSION}" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Build and push image (with SBOM and provenance)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          sbom: true
          provenance: mode=max
          tags: |
            maskedkunsiquat/itinerary-generator:latest
            maskedkunsiquat/itinerary-generator:${{ steps.version.outputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}
